// ============================================================
//  app.js — Project Tasks
//  Connects to Supabase and handles all CRUD operations
// ============================================================

// ── 1. SUPABASE SETUP ────────────────────────────────────────
// Replace these two values with YOUR Supabase project details
// (You will get them from supabase.com → your project → Settings → API)
const SUPABASE_URL = "YOUR_SUPABASE_URL";       // e.g. https://abcxyz.supabase.co
const SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY";  // long string starting with eyJ

// Create the Supabase client (supabase-js is loaded via CDN in index.html)
const { createClient } = supabase;
const db = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// ── 2. APP STATE ──────────────────────────────────────────────
let tasks = [];          // Array holding all tasks from Supabase
let currentFilter = "all";  // Which filter tab is active
let editingId = null;    // Which task is being edited in the modal

// ── 3. BOOT ──────────────────────────────────────────────────
// Runs as soon as the page loads
document.addEventListener("DOMContentLoaded", async () => {
  setTodayDate();
  await loadTasks();
  setupEnterKey();
});

// Show today's date in the header
function setTodayDate() {
  const el = document.getElementById("today-date");
  el.textContent = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric"
  });
}

// Allow pressing Enter in the input to add a task
function setupEnterKey() {
  document.getElementById("task-input").addEventListener("keydown", e => {
    if (e.key === "Enter") addTask();
  });
}

// ── 4. LOAD TASKS FROM SUPABASE ──────────────────────────────
async function loadTasks() {
  // .from("tasks") → selects the "tasks" table
  // .select("*")   → fetches all columns
  // .order("created_at", { ascending: false }) → newest first
  const { data, error } = await db
    .from("tasks")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) {
    showToast("⚠ Could not load tasks. Check Supabase config.");
    console.error("Supabase load error:", error.message);
    return;
  }

  tasks = data || [];
  renderAll();
}

// ── 5. ADD TASK ───────────────────────────────────────────────
async function addTask() {
  const input    = document.getElementById("task-input");
  const priority = document.getElementById("priority-select").value;
  const text     = input.value.trim();
  const errorEl  = document.getElementById("input-error");

  // Validation — don't allow empty tasks
  if (!text) {
    errorEl.textContent = "Please enter a task before adding.";
    input.focus();
    return;
  }
  errorEl.textContent = "";

  // Build the record to insert into Supabase
  // The "tasks" table has: id, text, priority, completed, created_at
  const newTask = {
    text: text,
    priority: priority,
    completed: false
    // id and created_at are auto-generated by Supabase
  };

  // .insert([newTask]) inserts one row
  // .select()          returns the inserted row (so we get the auto id)
  const { data, error } = await db
    .from("tasks")
    .insert([newTask])
    .select()
    .single();

  if (error) {
    showToast("⚠ Could not add task.");
    console.error("Insert error:", error.message);
    return;
  }

  // Add new task to the top of our local array
  tasks.unshift(data);
  input.value = "";
  renderAll();
  showToast("Task added ✓");
}

// ── 6. TOGGLE COMPLETE / INCOMPLETE ──────────────────────────
async function toggleTask(id) {
  const task = tasks.find(t => t.id === id);
  if (!task) return;

  const newStatus = !task.completed;

  // .update({ completed: newStatus }) → changes one column
  // .eq("id", id)                     → WHERE id = id
  const { error } = await db
    .from("tasks")
    .update({ completed: newStatus })
    .eq("id", id);

  if (error) {
    showToast("⚠ Could not update task.");
    console.error("Update error:", error.message);
    return;
  }

  // Update our local copy
  task.completed = newStatus;
  renderAll();
  showToast(newStatus ? "Marked as complete ✓" : "Marked as pending");
}

// ── 7. OPEN EDIT MODAL ────────────────────────────────────────
function openEdit(id) {
  const task = tasks.find(t => t.id === id);
  if (!task) return;

  editingId = id;

  const modalInput    = document.getElementById("modal-input");
  const modalPriority = document.getElementById("modal-priority");

  // Pre-fill the modal with current values
  modalInput.value = task.text;

  // Build priority dropdown inside modal
  modalPriority.innerHTML = ["low","medium","high"].map(p =>
    `<option value="${p}" ${task.priority === p ? "selected" : ""}>${capitalize(p)}</option>`
  ).join("");

  document.getElementById("modal-overlay").classList.remove("hidden");
  modalInput.focus();
}

// Save edits back to Supabase
async function saveEdit() {
  const newText     = document.getElementById("modal-input").value.trim();
  const newPriority = document.getElementById("modal-priority").value;

  if (!newText) return;

  // .update({ text, priority }) → updates two columns at once
  const { error } = await db
    .from("tasks")
    .update({ text: newText, priority: newPriority })
    .eq("id", editingId);

  if (error) {
    showToast("⚠ Could not save edit.");
    console.error("Edit error:", error.message);
    return;
  }

  // Update local array
  const task = tasks.find(t => t.id === editingId);
  if (task) { task.text = newText; task.priority = newPriority; }

  closeModalDirect();
  renderAll();
  showToast("Task updated ✓");
}

// Close modal when clicking the dark overlay behind it
function closeModal(e) {
  if (e.target === document.getElementById("modal-overlay")) closeModalDirect();
}
function closeModalDirect() {
  document.getElementById("modal-overlay").classList.add("hidden");
  editingId = null;
}

// ── 8. DELETE TASK ────────────────────────────────────────────
async function deleteTask(id) {
  // .delete()     → deletes the row
  // .eq("id", id) → WHERE id = id
  const { error } = await db
    .from("tasks")
    .delete()
    .eq("id", id);

  if (error) {
    showToast("⚠ Could not delete task.");
    console.error("Delete error:", error.message);
    return;
  }

  // Remove from local array
  tasks = tasks.filter(t => t.id !== id);
  renderAll();
  showToast("Task deleted");
}

// ── 9. CLEAR ALL COMPLETED ───────────────────────────────────
async function clearCompleted() {
  const completed = tasks.filter(t => t.completed);
  if (completed.length === 0) { showToast("No completed tasks to clear."); return; }

  // .in("id", [...ids]) → WHERE id IN (id1, id2, ...)
  const ids = completed.map(t => t.id);
  const { error } = await db
    .from("tasks")
    .delete()
    .in("id", ids);

  if (error) { showToast("⚠ Could not clear tasks."); return; }

  tasks = tasks.filter(t => !t.completed);
  renderAll();
  showToast(`Cleared ${ids.length} completed task${ids.length > 1 ? "s" : ""}`);
}

// ── 10. FILTER ────────────────────────────────────────────────
function setFilter(filter) {
  currentFilter = filter;

  // Update active button style
  document.querySelectorAll(".filter-btn").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.filter === filter);
  });

  renderAll();
}

// ── 11. RENDER ────────────────────────────────────────────────
// This function re-draws the whole task list every time data changes
function renderAll() {
  updateStats();
  renderList();
}

// Update the 4 stat cards at the top
function updateStats() {
  const total   = tasks.length;
  const done    = tasks.filter(t => t.completed).length;
  const pending = total - done;
  const pct     = total === 0 ? 0 : Math.round((done / total) * 100);

  document.getElementById("stat-total").textContent   = total;
  document.getElementById("stat-done").textContent    = done;
  document.getElementById("stat-pending").textContent = pending;
  document.getElementById("ring-pct").textContent     = pct + "%";

  // Animate the progress ring (SVG stroke-dasharray trick)
  document.getElementById("ring-fill").setAttribute(
    "stroke-dasharray", `${pct} ${100 - pct}`
  );
}

// Render the visible task cards
function renderList() {
  const list  = document.getElementById("task-list");
  const empty = document.getElementById("empty-state");

  // Filter tasks based on active tab
  const visible = tasks.filter(t => {
    if (currentFilter === "pending")  return !t.completed;
    if (currentFilter === "done")     return  t.completed;
    return true;
  });

  if (visible.length === 0) {
    list.innerHTML = "";
    empty.classList.remove("hidden");
    return;
  }
  empty.classList.add("hidden");

  list.innerHTML = visible.map(task => buildTaskHTML(task)).join("");
}

// Build the HTML string for a single task card
function buildTaskHTML(task) {
  const dateStr = new Date(task.created_at).toLocaleDateString("en-US", {
    month: "short", day: "numeric"
  });

  const priorityBadge = task.completed
    ? `<span class="badge badge-done">Done</span>`
    : `<span class="badge badge-${task.priority}">${capitalize(task.priority)}</span>`;

  return `
    <div class="task-item priority-${task.priority} ${task.completed ? "completed" : ""}"
         id="task-${task.id}">

      <!-- Checkbox to toggle complete/incomplete -->
      <input
        type="checkbox"
        class="task-checkbox"
        ${task.completed ? "checked" : ""}
        onchange="toggleTask('${task.id}')"
        title="Toggle complete"
      />

      <!-- Task text and meta info -->
      <div class="task-body">
        <div class="task-text">${escapeHTML(task.text)}</div>
        <div class="task-meta">
          ${priorityBadge}
          <span class="task-date">Added ${dateStr}</span>
        </div>
      </div>

      <!-- Edit and Delete buttons -->
      <div class="task-actions">
        <button class="btn-icon" onclick="openEdit('${task.id}')" title="Edit task">✎</button>
        <button class="btn-icon del" onclick="deleteTask('${task.id}')" title="Delete task">✕</button>
      </div>
    </div>
  `;
}

// ── 12. HELPERS ───────────────────────────────────────────────
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// Prevent XSS — never render raw user text as HTML
function escapeHTML(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}

// Show a toast notification for 2.5 seconds
function showToast(message) {
  const toast = document.getElementById("toast");
  toast.textContent = message;
  toast.classList.add("show");
  setTimeout(() => toast.classList.remove("show"), 2500);
}
